spring:
    datasource:
        url: jdbc:mysql://localhost:3306/crm?createDatabaseIfNotExist=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: 
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect